### ISSUE TITLE
Xcode does not have an iOS framework target

### ISSUE THREAD

**Issue by Danappelxx** [AlwaysRightInstitute/SwiftSockets#18]
This is not an issue for Cocoapods since it just builds the source files, but when the framework is built with Carthage (or just Xcode, really), there is no target to output an iOS framework.

Ideally, there would be the framework targets `SwiftSockets-OSX` and `SwiftSockets-iOS`, both with the same product name. This is a bit of annoying to do, so I'll do it for you! I just wanted to check in and ask if this is alright before I do.

By the way, we've been using SwiftSockets for Taylor for a couple weeks and haven't had any issues with it yet! Great job :+1:

**Comment by helje5** [comment]
Sure, go ahead. Maybe also include a simple iOS demo app, similar to the OSX ones?
