### ISSUE TITLE
support SSL/TLS?

### ISSUE THREAD

**Issue by ghost** [AlwaysRightInstitute/SwiftSockets#24]

**Comment by helje5** [comment]
SSL is not provided by the standard C/Unix library, so we would depend on some 3rd party library like OpenSSL - which is kinda against the idea of SwiftSockets. Though admittedly OpenSSL should be on pretty much any system (hence I keep the issue open for now). My feeling though is that this should be build on top of SwiftSockets, not as part of it. Something like SwiftSSLSockets. Either way it shouldn't be too hard to implement.

**Comment by zaferaydn** [comment]
is there any progress of implementing SSL sockets. I want to use this library to make a connection to a tcp server. But in the feature, i will have to connect to a SSL socket too. So SSL/TLS support is important for me.

**Comment by helje5** [comment]
As mentioned SSL should not be part of this thing but rather be a separate thing building on top of SwiftSockets. Maybe someone can hook it up with [BlueSSLService](https://github.com/IBM-Swift/BlueSSLService).

P.S.: Wrt my previous comment: OpenSSL is not available on Apple platforms by default anymore. This makes it even less likely that SwiftSockets itself includes SSL.
