### ISSUE TITLE
How do I print out a client's message on server side?

### ISSUE THREAD

**Issue by ProgrammerMatt** [AlwaysRightInstitute/SwiftSockets#26]
If I'm listening on port 8080, and I have a client (Active socket) write to the socket, how do I print from the serverside that message?

 let socket = PassiveSocket<sockaddr_in>(address: sockaddr_in(port: 8080))!
            .listen(dispatch_get_global_queue(0, 0), backlog: 5) {
                print("Wait, someone is attempting to talk to me!")
                
                $0.close()
                print("All good, go ahead!")
        }
    }

I think it would go somewhere in here, but I have no idea where to go from that.

thanks

**Comment by helje5** [comment]
GitHub issues are for reporting bugs/feature requests on the software, NOT for asking question. Please don't do that again. A good programming QA site is [StackOverflow](http://stackoverflow.com).

Having said that, a full example is included in the source: [EchoServer](https://github.com/AlwaysRightInstitute/SwiftSockets/blob/master/Sources/SwiftyEchoDaemon/EchoServer.swift)
