### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by nneuberger1** [AlwaysRightInstitute/SwiftSockets#27]
Does this project support Swift 3 fully?

I'm currently upgrading our projects to swift 3 and started using this with the older versions of swift, but after upgrading I'm getting several failures on comilation of this pulled in as a Pod. 

I've tried the standard cocoapods that's latest and another branch.

 # pod 'SwiftSockets', '~> 0.22.10'
    pod 'SwiftSockets', :git => "https://github.com/AlwaysRightInstitute/SwiftSockets", :tag => '0.22.8'

Here's a few errors from the 0.22.8 branch.

/Users/nneuberger/ws/kiosk-ios-app/Pods/SwiftSockets/Sources/SwiftSockets/SocketAddress.swift:127:18: Value of type 'sockaddr_in' has no member 'dynamicType'

/Users/nneuberger/ws/kiosk-ios-app/Pods/SwiftSockets/Sources/SwiftSockets/SocketAddress.swift:127:18: Value of type 'sockaddr_in' has no member 'dynamicType'
/Users/nneuberger/ws/kiosk-ios-app/Pods/SwiftSockets/Sources/SwiftSockets/SocketAddress.swift:266:16: Value of type 'sockaddr_in6' has no member 'dynamicType'

/Users/nneuberger/ws/kiosk-ios-app/Pods/SwiftSockets/Sources/SwiftSockets/UnixUtils.swift:39:11: 'dispatch_source_t' is unavailable in Swift

There are several other errors as well.

**Comment by helje5** [comment]
This project doesn't support Swift 3. I'll keep this open, maybe I should port it.

**Comment by helje5** [comment]
I've created a `feature/swift3` branch which compiles with Swift 3. Untested. Also: don't know how CocoaPods deal with Swift 3 vs Swift 2 and what people want here. Should master/develop be on Swift 3 and Swift 2 moved to a legacy branch? Swift 3 final doesn't really support a Swift 2&3 project anymore.

**Comment by nneuberger1** [comment]
Thanks, do you know the best branch / tag that could help support XCode 8 and Swift 2.3 in the interim?

**Comment by helje5** [comment]
Develop/master doesn't work with Xcode 8/Swift 2.3? That would be a separate issue.

**Comment by helje5** [comment]
OK, #58ee85ad274ebf475a3dafb19a9466a7c2b40d38 is building fine on macOS/Linux Swift 3 in Travis and a small tests seems to confirm it is working.

So the only pending question is how to proceed with CocoaPods and whether Swift 2.x still matters.

**Comment by nneuberger1** [comment]
Thanks for the help.   I'm still trying to push migrating to Swift 3.0 and this library for our application, but were having to put a patch in for swift 2.3 support because our 3.0 migration is taking much longer than anticipated.

On the 2.3 / branch master issue.  I'm still seeing compilation issues with the "Legacy" option.  There aren't many errors so far, so I could possibly fork and submit a pull request.

Here's some of the swift 2.3 errors:

/Users/nneuberger/ws/kiosk-ios-app/Pods/SwiftSockets/Sources/SwiftSockets/PassiveSocket.swift:120:11: Initializer for conditional binding must have Optional type, not 'dispatch_source_t' (aka 'OS_dispatch_source')

/Users/nneuberger/ws/kiosk-ios-app/Pods/SwiftSockets/Sources/SwiftSockets/ActiveSocket.swift:328:11: Initializer for conditional binding must have Optional type, not 'dispatch_data_t' (aka 'OS_dispatch_data')
/Users/nneuberger/ws/kiosk-ios-app/Pods/SwiftSockets/Sources/SwiftSockets/ActiveSocket.swift:357:11: Initializer for conditional binding must have Optional type, not 'dispatch_data_t' (aka 'OS_dispatch_data')

So far, that's the only 3 errors that I see when using 2.3 and pulling master using cocoapods.

pod 'SwiftSockets', :git => "https://github.com/AlwaysRightInstitute/SwiftSockets", :branch => 'master'

Thanks again for all of your help.

**Comment by nneuberger1** [comment]
If you think it's a legit error, I can create a new issue here on the project for clarity.

**Comment by nneuberger1** [comment]
I created a pull request to help with the Swift 2.3 support.

https://github.com/AlwaysRightInstitute/SwiftSockets/pull/28

**Comment by helje5** [comment]
Swift 3 support is available in the feature/swift3 branch. Maybe we need another issue on how/what to submit to CocoaPods upstream.
