### ISSUE TITLE
CocoaPods?

### ISSUE THREAD

**Issue by helje5** [AlwaysRightInstitute/SwiftSockets#5]
Does it make sense to provide the ARISockets framework as a CocoaPod? Maybe, just for the heck of it.

**Comment by Danappelxx** [comment]
👍

**Comment by izqui** [comment]
That'd be useful!

**Comment by helje5** [comment]
Pull requests are welcome! ;-)

**Comment by izqui** [comment]
There you go!

**Comment by helje5** [comment]
OK, integrated and pushed to pods trunk. Let me know if something is wrong with this.

**Comment by izqui** [comment]
Great! It is working perfectly for me :)
