### ISSUE TITLE
Without Foundation

### ISSUE THREAD

**Issue by darkclouder** [AlwaysRightInstitute/SwiftSockets#9]
Hi, I saw this project and it goes into the direction of what I look for, but you still use the Foundation Framework.
The question is: is this possible with the standard library and C libraries only? I search for that having the upcoming Linux compiler in mind because I was planning to build a server-side network application on Swift that would run on a Linux system. But for that there has to be a network library that is completely platform independent and rely on the existing standard libraries of that system.
Are you going to do that and/or do you see a way to do so?

**Comment by helje5** [comment]
On 09 Oct 2015, at 15:09, darkclouder <notifications@github.com> wrote:
> Hi, I saw this project and it goes into the direction of what I look for, but you still use the Foundation Framework.

Does it? It shouldn’t. The ‘apps’ link to it, but SwiftSockets itself should not use anything Foundation.
(well, except for Swift itself maybe)

> The question is: is this possible with the standard library and C libraries only?

The SwiftSockets themselves are not supposed to use any Foundation things. Please elaborate where they do, file an issue.

> I search for that having the upcoming Linux compiler in mind because I was planning to build a server-side network application on Swift that would run on a Linux system. But for that there has to be a network library that is completely platform independent and rely on the existing standard libraries of that system.
> Are you going to do that and/or do you see a way to do so?

We don’t know yet what the ‘upcoming Linux compiler’ is going to provide. Does it even come with the standard Swift library? What about GCD? What about the parts of the Swift library which are implemented using Foundation/CFFoundation? etc.

My guess is that Apple is just going to OpenSource the Swift clang frontend. Linux developers would need to come up with the backing infrastructure (similar to libFoundation or GNUstep). But we’ll see.

But yes, SwiftSockets itself isn’t using / supposed-to-use any Foundation. So it’s kinda what you want.
Though SwiftSockets is more an experiment. A real thing should be implemented using GCD channels (and I have some prototypes of that). And not in Swift :-)

hh

**Comment by darkclouder** [comment]
Ah, yes, I noticed you actually import Darwin instead of Foundation. I'm still not sure if something similar (calling it Darwin would be inappropriate for a linux system) to Darwin will be included in the linux compiler. I played a bit around with the swift cli (swiftc) and when you want to use Darwin or Foundation for your program you have to specify an SDK to compile the sources. Based on that fact and on the information on the offical Swift developer site I'm pretty sure the linux compiler will include and only include the Swift Standard Library.

**Comment by helje5** [comment]
Guesswork. We'll see when they release it. As mentioned SwiftSockets only uses standard Unix APIs and of course GCD.
